import { SITE_DESCRIPTION } from "@/config";
import { AppContext } from "@/pages/_app";
import { ChildProps } from "@/types/sharedTypes";
import { Container } from "@mantine/core";
import Head from "next/head";
import { useRef, useState, useEffect } from "react";
import { BaseHead } from "../transferred/BaseHead";
import { Footer } from "../transferred/Footer";

export type BaseLayoutProps = ChildProps & {
    renderHeader: (ref: React.RefObject<HTMLDivElement>) => JSX.Element;
    pageName: string;
};

export const BaseLayout = ({ pageName, renderHeader, children }: BaseLayoutProps) => {
    const ref = useRef<HTMLDivElement>(null);
    const [height, setHeight] = useState<number>(0);
    const [windowHeight, setWindowHeight] = useState<number>(0);
    useEffect(() => {
        if (ref && ref.current) {
            setHeight(ref.current?.clientHeight);
        }
    }, []);

    useEffect(() => {
        const handleResize = () => {
            if (ref && ref.current) {
                setHeight(ref.current?.clientHeight);
            }
        };
        window.addEventListener("resize", handleResize);
        return () => {
            return window.removeEventListener("resize", handleResize);
        };
    }, [height]);

    useEffect(() => {
        const wh = window.screen.height;
        setWindowHeight(wh);
    }, []);

    return (
        <>
            <Head>
                <title>{pageName}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <BaseHead title={pageName} description={SITE_DESCRIPTION} image={"placeholder-social.jpg"} />
            </Head>
            {renderHeader(ref)}
            <div style={{ height: `${height}px` }} className="w-full h-auto bg-primary dark:bg-primary-dark"></div>
            <main style={{ minHeight: `${windowHeight - height}px` }} className="bg-primary dark:bg-primary-dark">
                <Container fluid className="bg-primary dark:bg-primary-dark">
                    {children}
                </Container>
            </main>
            <Footer />
        </>
    );
};
